<script setup>
import { ref, onMounted, getCurrentInstance, onBeforeMount } from "vue";
import ClassDetail from "../components/ClassDetail.vue";
import { mdiConsoleNetworkOutline } from "@mdi/js";
import axios from "axios";

const lectureCode = ref(null);
// 後でこのコメントアウトは外す！
const classDetailData = ref(null);

const getclassDetailData = async(lectureCode) => {

  const data = {
    lectureCode:lectureCode.value
  }

  try {
    const response = await axios.post("/api/searchByLectureCode", data);
    // const response = await axios.post("/api/hasLectureCode", data);
    console.log(response.data);

    return response.data;

    // その他の処理
  } catch (error) {
    if (error.response) {
      // サーバーからのエラーレスポンスがある場合
      console.error(error.response.data); // エラーレスポンスをコンソールに出力
    } else {
      // リクエストがサーバーに届かなかった場合など
      console.error(error.message);
    }
  }
};

onBeforeMount(async() => {
  // contextから$routeを取得する
  const { $route } = getCurrentInstance().appContext.config.globalProperties;
  //lectureIdを$routeから取得
  lectureCode.value = $route.params.lectureCode;
  console.log(`lecture code  is ${lectureCode.value}`);

  classDetailData.value = await getclassDetailData(lectureCode);
  // classDetailData.value = getclassDetailData(lectureCode.value);

  // console.log(classDetailData2)
  console.log(classDetailData.value);
});

// サンプルデータ
const classDetailData2 = {
  classInformationData: {
    lectureName: "一攫千金特論",
    teacherName: "服部淳生",
    classInformationDataList: [
      {
        category: "プログラミング",
        faculty: "情報科学部",
        grade: "1年生",
        lectureCode: "ABC123",
        lectureDetailId: 1,
        location: "London",
        syllabusUrl: "https://google.com",
        lectureDetailTimes: [
          {
            year: 2024,
            term: "2ターム",
            dayOfWeek: "月曜日",
            timePeriod: "12限",
          },
          {
            year: 2023,
            term: "4ターム",
            dayOfWeek: "月曜日",
            timePeriod: "13限",
          },
        ],
      },
      {
        category: "プログラミング",
        faculty: "情報科学部",
        grade: "1年生",
        lectureCode: "ABC345",
        lectureDetailId: 1,
        location: "Birmingham",
        syllabusUrl: "https://google.com",
        lectureDetailTimes: [
          {
            year: 2024,
            term: "2ターム",
            dayOfWeek: "月曜日",
            timePeriod: "14限",
          },
          {
            year: 2023,
            term: "4ターム",
            dayOfWeek: "月曜日",
            timePeriod: "15限",
          },
        ],
      },
    ],
  },
  //総合評価
  classRadarChartData: {
    creditLevel: 2,
    interestLevel: 3,
    skillLevel: 5,
  },
  //レビュワーからのデータの統計
  classBarGraphData: {
    grades: {
      S: 20,
      A: 30,
      B: 30,
      C: 30,
      D: 80,
    },
    attendanceConfirm: {
      everyday: 1,
      sometimes: 20,
      none: 200,
    },
    pastExamPossesion: {
      yes: 20,
      no: 300,
    },
    weeklyAssignments: {
      yes: 20,
      no: 300,
    },
    midtermAssignments: {
      yes: 300,
      no: 1,
    },
    finalAssignments: {
      yes: 300,
      no: 1,
    },
  },
  reviewDataList: [
    {
      reviewId: "0001",
      userName: "Yuki Takahara",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "あり",
      pastExamPossesion: "なし",
      weeklyAssignments: "あり",
      midtermAssignments: "あり",
      finalAssignments: "あり",
    },
    {
      reviewId: "0002",
      userName: "Cristiano Ronaldo",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "Siuuuuuuuuuuu!!!!!",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0003",
      userName: "Johann Cruyff",
      totalEvaluation: 3,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0004",
      userName: "Lionel Messi",
      totalEvaluation: 2,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "Ankara Messi",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0005",
      userName: "Dusan Vlahovic",
      totalEvaluation: 5,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0006",
      userName: "Adrien Rabiot",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0007",
      userName: "Weston McKennie",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0008",
      userName: "Filip Kostic",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0009",
      userName: "Hans Nicolussi Caviglia",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0010",
      userName: "Timothy Weah",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0011",
      userName: "Danilo",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0012",
      userName: "Bremer",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0013",
      userName: "Federico Gatti",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0014",
      userName: "Wojciech Szczesny",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0015",
      userName: "Manuel Locatelli",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0016",
      userName: "Kenan Yildiz",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Federico Chiesa",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Rodaldinho",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Andres Iniesta",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Neymar",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Xabi Hernandez",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Luiz Suarez",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Ronaldo",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Puyol",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Diego Armando Maradona",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Samuel Eto'o",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Busquets",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Gerard Pique",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Figo",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Theiry Henry",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Zlatan Ibrahimovic",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Ansu Fati",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Federico Chiesa",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Federico Chiesa",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Federico Chiesa",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Federico Chiesa",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
    {
      reviewId: "0018",
      userName: "Federico Chiesa",
      totalEvaluation: 4,
      attendanceYear: "2023",
      createdAt: "2024-01-13",
      comments: "とてもためになる授業だと思う",
      creditLevel: 3,
      interestLevel: 2,
      skillLevel: 3,
      grades: "優",
      attendanceConfirm: "",
      pastExamPossesion: "",
      weeklyAssignments: "",
      midtermAssignments: "",
      finalAssignments: "",
    },
  ],
};
</script>

<template>
  aa
  <!-- {{ classDetailData }} -->
  <ClassDetail :classDetailData="classDetailData"></ClassDetail>
</template>