version: '3'
services:
  l10dev-nginx:
    container_name: "l10dev-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - l10dev-app
    ports:
      - 9001:80
    volumes:
      - ./:/src

  l10dev-app:
    container_name: "l10dev-app"
    build:
      context: ./docker/php
    depends_on:
      - l10dev-mysql
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  l10dev-mysql:
    image: mysql:8.0.33
    command: --max_allowed_packet=32505856
    container_name: "l10dev-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=l10dev
    ports:
      - 3306:3306

  l10dev-redis:
    image: redis:alpine
    container_name: "l10dev-redis"
    ports:
      - 16379:6379
